###
PUT http://localhost:8080/api/users/1/requestedTasks/4
###
PUT http://localhost:8080/api/users/1/requestedTasks/5
###
PUT http://localhost:8080/api/users/1/requestedTasks/6
###
PUT http://localhost:8080/api/users/1/requestedTasks/7
###
PUT http://localhost:8080/api/users/2/requestedTasks/1
###
PUT http://localhost:8080/api/users/2/requestedTasks/2
###
PUT http://localhost:8080/api/users/2/requestedTasks/3
###
PUT http://localhost:8080/api/users/2/requestedTasks/7
###
PUT http://localhost:8080/api/users/3/requestedTasks/1
###
PUT http://localhost:8080/api/users/3/requestedTasks/4