POST http://localhost:8080/api/user
Content-Type: application/json

{
  "id": "1",
   "nickname": "A",
   "rating": 5.0,
   "major":
   {
       "semester": 1,
       "name": "Maths"
   },
  "courses": [
    {
      "id": "c1",
      "name": "Java"
    }
  ]

}

###
