spring:
  datasource:
#    url: jdbc:h2:file:./data/demo
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: false
  cloud.discovery.client.simple.instances:
    auth-app:
      - instanceId: instance1
        serviceId: jsos-app
        uri: http://localhost:2137


#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password:
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
#    defer-datasource-initialization: true

